languageCode = "en-us"
title = "Karl Taylor"
baseurl = "https://www.karljtaylor.com/"
theme = "aerial"

[params]
  name = "Karl Taylor"
  about = "Marketer &nbsp;&bull;&nbsp; Human &nbsp;&bull;&nbsp; Lover of Sandwiches"
  copyright = "Karl Taylor"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/karljtaylor"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/rolyatjlrak"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://instagram.com/karljtaylor"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:hello@karljtaylor.com?subject=hey%2C%20karl!&amp;body=hello!"

[[params.social]]
  medium = "Blog"
  icon = "pencil"
  link = "https://blog.karljtaylor.com"

[[params.social]]
    medium = "linkedin"
    icon = "linkedin"
    link = "https://linkedin.com/in/karljtaylor"
