baseurl = "https://blog.karljtaylor.com/"
canonifyURLs = false
disqusShortname = "karljtaylor"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Karl Taylor"
[SEO]
canonifyURLs = false
enableRobotsTXT = true
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[params]
categoriesbycount = true
customcss = ["default"]
customjs = ["default"]
description = "Karl Taylor's Blog"
disable_highlight = false
dynamictitles = true
faviconversion = ""
highlightjscdn = "//cdn.bootcss.com"
highlightjslang = ["r", "yaml", "css"]
highlightjstheme = "github"
highlightjsversion = "9.11.0"
includereadingtime = true
loadfavicon = false
mathjaxcdn = "//cdn.bootcss.com"
mathjaxversion = "2.7.1"
navbartitle = "karl's blog"
rssappearatbottom = true
rssappearattop = true
showsidebarcategories = true
socialappearatbottom = true
socialappearattop = true
socialshare = true
socialshareemail = true
socialsharefacebook = true
socialsharegoogleplus = false
socialsharelinkedin = true
socialsharepinterest = true
socialsharereddit = true
socialsharestumbleupon = true
socialsharetwitter = true
viewmorepostlink = "/blog/"
[params.intro]
about = "Marketer  •  Human  •  Explorer of Worlds"
header = "karl taylor"
paragraph = "Marketer  •  Human  •  Explorer of Worlds"
[params.intro.pic]
alt = "Karl Taylor"
circle = false
imperfect = true
src = "assets/karljtaylor-typewriter-image.png"
width = ""
[params.postamount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[permalinks]
post = "/post/:filename/"
[social]
behance = "karljtaylor"
email = "hello@karljtaylor.com"
facebook = "rolyatjlrak"
instagram = "karljtaylor"
linkedin = "karljtaylor"
medium = "karljtaylor"
pinterest = "karljtaylor"
quora = "Karl-Taylor-11"
reddit = "karljtaylor"
telegram = "karljtaylor"
twitter = "karljtaylor"
whatsapp = "+17206190810"
youtube = "channel/UCUl7hXpIVxQHdwWIAzkzdmA"
[params.sidebar]
categories          = false
