---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: content
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: blog
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/assets
public_path: "/public/static/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
