---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/pages/contact.md
- content/pages/contact.md
- content/pages/hey--y-all.md
- content/pages/hey--y-all.md
- content/pages/privacy-policy.md
- content/pages/privacy-policy.md
- content/pages/the-end-is-not-yet.md
- content/pages/the-end-is-not-yet.md
