---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- post/this-is-a-new-post.md
- pages/hey--y-all.md
- pages/contact.md
